= Lab 5 - Publishing to Openshift 

There are several ways to deploy an application into openshift. Directly from the git repository using S2I, 
directly from the machine using binary deployment or directly from a Docker image.

On this lab we will use the binary deployment option, uploading the code directly from our machine to Openshift server.
For it works, we will need the `oc` client working in our local machine.

== Openshift deploy

First login into Openshift:

    oc login {openshift-host} -u evals01@example.com -p Password1

Once  that we are logged in, and in the specific project, let's do the deploy.

    mvn fabric8:deploy -Popenshift

It can take a while depending on your network performance. 

The *fabric8:deploy* uses the oc client authentication under the hood. So it explains all the dark magic during this process. 

It's important to mention that it uses a binary deployment, but you can use the strategy that you want. 

After fabric8:deploy, take a look in the target field inside the project, to be more specific
look into: target/docker/fuse-workshop/latest/build.

Open the Java Console, and check the metrics available. 
Also, take a look into the Diagram.

[time=10]

[type=verification]
Are you seeing your application in Openshift?
